apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cw-frontend
  template:
    metadata:
      labels:
        app: cw-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: cw-frontend
          image: ghcr.io/tumbler-cp/cwfront:latest
          env:
            - name: REACT_APP_API_URL
              value: "http://spring-backend:8080"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cw-frontend
spec:
  selector:
    app: cw-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
